name: Build Winhider App

on:
  push:
    branches:
      - main         # For untagged builds like "latest"
    tags:
      - 'v*'         # For tagged releases like v1.0.0
  pull_request:
    types: [closed]
  workflow_dispatch: # Manual trigger via GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Project
        run: |
          msbuild Winhider.sln /p:Configuration=Release /p:Platform=x64 -m
          msbuild Winhider.sln /p:Configuration=Release /p:Platform=x86 -m
          
      - name: Sign Release Binaries
        run: sign.cmd -p "\"${{ secrets.WINHIDER_CERT_SIGN_PASSWORD }}\""

      - name: Generate zip bundle
        run: 7z a -tzip Winhider.zip .\hide_hotkey.ahk .\Build\bin\Release\*.dll .\Build\bin\Release\*.exe

      - name: Build Installer
        run: iscc .\Misc\inno.iss
        
      - name: Sign Installer
        run: sign.cmd -i -p "\"${{ secrets.WINHIDER_CERT_SIGN_PASSWORD }}\""

      - name: Publish latest pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GH_WORKFLOW_TOKEN_WINHIDER }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            Winhider.zip
            Misc/Output/WinhiderInstaller.exe

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Publish tagged release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GH_WORKFLOW_TOKEN_WINHIDER }}"
          prerelease: false
          files: |
            Winhider.zip
            Misc/Output/WinhiderInstaller.exe
